import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class PdfService {
  static Future<void> generateExpenseReport(
      List<Map<String, dynamic>> expenses) async {
    final pdf = pw.Document();

    double total = 0;

    for (var expense in expenses) {
      total += (expense['amount'] as num).toDouble();
    }

    final today = DateTime.now();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,

        header: (context) => pw.Container(
          padding: const pw.EdgeInsets.only(bottom: 10),
          decoration: const pw.BoxDecoration(
            border: pw.Border(
              bottom: pw.BorderSide(width: 1),
            ),
          ),
          child: pw.Row(
            mainAxisAlignment:
                pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text(
                "Expense Tracker",
                style: pw.TextStyle(
                  fontSize: 24,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              pw.Text(
                "${today.day}/${today.month}/${today.year}",
              ),
            ],
          ),
        ),

        footer: (context) => pw.Align(
          alignment: pw.Alignment.centerRight,
          child: pw.Text(
            "Page ${context.pageNumber} of ${context.pagesCount}",
            style: const pw.TextStyle(fontSize: 10),
          ),
        ),

        build: (context) => [

          pw.SizedBox(height: 15),

          pw.Center(
            child: pw.Text(
              "Expense Report",
              style: pw.TextStyle(
                fontSize: 22,
                fontWeight: pw.FontWeight.bold,
              ),
            ),
          ),

          pw.SizedBox(height: 20),

          pw.Container(
            padding: const pw.EdgeInsets.all(12),
            decoration: pw.BoxDecoration(
              color: PdfColors.grey300,
              borderRadius:
                  pw.BorderRadius.circular(8),
            ),
            child: pw.Row(
              mainAxisAlignment:
                  pw.MainAxisAlignment.spaceAround,
              children: [

                pw.Column(
                  children: [
                    pw.Text(
                      "Total Expenses",
                      style: pw.TextStyle(
                        fontWeight:
                            pw.FontWeight.bold,
                      ),
                    ),
                    pw.Text(
                      "Rs. ${total.toStringAsFixed(2)}",
                    ),
                  ],
                ),

                pw.Column(
                  children: [
                    pw.Text(
                      "Entries",
                      style: pw.TextStyle(
                        fontWeight:
                            pw.FontWeight.bold,
                      ),
                    ),
                    pw.Text(
                      expenses.length.toString(),
                    ),
                  ],
                ),
              ],
            ),
          ),

          pw.SizedBox(height: 25),

          pw.Table.fromTextArray(
            border: pw.TableBorder.all(),
            headerStyle: pw.TextStyle(
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.white,
            ),
            headerDecoration: const pw.BoxDecoration(
              color: PdfColors.blue700,
            ),

            headers: const [
              "Title",
              "Category",
              "Amount",
              "Date",
            ],

            data: expenses.map((expense) {
              return [
                expense['title'],
                expense['category'],
                "Rs. ${expense['amount']}",
                expense['date']
                    .toString()
                    .split(" ")
                    .first,
              ];
            }).toList(),
          ),

          pw.SizedBox(height: 20),

          pw.Align(
            alignment: pw.Alignment.centerRight,
            child: pw.Text(
              "Grand Total : Rs. ${total.toStringAsFixed(2)}",
              style: pw.TextStyle(
                fontSize: 18,
                fontWeight: pw.FontWeight.bold,
              ),
            ),
          ),

          pw.SizedBox(height: 30),

          pw.Center(
            child: pw.Text(
              "Generated by Expense Tracker App",
              style: const pw.TextStyle(
                fontSize: 12,
              ),
            ),
          ),
        ],
      ),
    );

    await Printing.layoutPdf(
      onLayout: (format) async => pdf.save(),
    );
  }
}